name: rt_env
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - basicsr==1.4.2
      - basicsr-fixed==1.4.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - facexlib==0.3.0
      - filelock==3.19.1
      - filterpy==1.4.5
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - future==1.0.0
      - gfpgan==1.3.8
      - grpcio==1.76.0
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - numba==0.62.1
      - numpy==2.1.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - realesrgan==0.3.0
      - requests==2.32.5
      - scikit-image==0.25.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.13.1
      - tb-nightly==2.21.0a20251023
      - tensorboard-data-server==0.7.2
      - tifffile==2025.5.10
      - tomli==2.3.0
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - yapf==0.43.0
prefix: C:\Users\Fredy Orellana\.conda\envs\rt_env
